import React, { useEffect, useRef } from "react";
import sdk from "@stackblitz/sdk";

const StackBlitzPreview = ({
  componentCode,
  title = "Component Preview",
  height = 500,
}) => {
  const containerRef = useRef(null);
  const vmRef = useRef(null);
  const [loading, setLoading] = React.useState(true);
  const [error, setError] = React.useState(null);

  useEffect(() => {
    if (!componentCode || !containerRef.current) return;

    const createProject = async () => {
      try {
        setLoading(true);
        setError(null);

        // Create project files
        const project = {
          files: {
            "public/index.html": `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>UI Alchemy Component</title>
  </head>
  <body>
    <div id="root"></div>
  </body>
</html>`,
            "src/index.js": `import React from 'react';
import { createRoot } from 'react-dom/client';
import App from './App';

const root = createRoot(document.getElementById('root'));
root.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);`,
            "src/App.js": `import React from 'react';
import RequestedComponent from './RequestedComponent';

function App() {
  return (
    <div style={{ 
      display: 'flex', 
      justifyContent: 'center', 
      alignItems: 'center', 
      padding: '20px', 
      minHeight: '100vh',
      fontFamily: 'sans-serif'
    }}>
      <RequestedComponent />
    </div>
  );
}

export default App;`,
            "src/RequestedComponent.jsx": componentCode,
            "package.json": JSON.stringify(
              {
                name: "ui-alchemy-component-preview",
                version: "0.1.0",
                private: true,
                dependencies: {
                  react: "^18.2.0",
                  "react-dom": "^18.2.0",
                  "react-scripts": "5.0.1",
                  "@mui/material": "^5.14.20",
                  "@mui/icons-material": "^5.14.19",
                  "@emotion/react": "^11.11.1",
                  "@emotion/styled": "^11.11.0",
                  "framer-motion": "^10.16.5",
                },
              },
              null,
              2
            ),
          },
          title: title || "UI Alchemy Component Preview",
          description: "Preview of a UI component generated by UI Alchemy",
          template: "create-react-app",
          dependencies: {
            react: "^18.2.0",
            "react-dom": "^18.2.0",
            "react-scripts": "5.0.1",
            "@mui/material": "^5.14.20",
            "@mui/icons-material": "^5.14.19",
            "@emotion/react": "^11.11.1",
            "@emotion/styled": "^11.11.0",
            "framer-motion": "^10.16.5",
            "lucide-react": "^0.503.0",
          },
        };

        // Create the VM
        vmRef.current = await sdk.embedProject(containerRef.current, project, {
          height,
          openFile: "src/RequestedComponent.jsx",
          terminalHeight: 0,
          view: "preview",
          hideDevTools: true,
          hideNavigation: true,
        });
      } catch (err) {
        console.error("StackBlitz error:", err);
        setError(err.toString());
      } finally {
        setLoading(false);
      }
    };

    createProject();

    return () => {
      // Cleanup if needed
      vmRef.current = null;
    };
  }, [componentCode, height, title]);

  // Show loading state if needed
  if (loading && !vmRef.current) {
    return (
      <div ref={containerRef} style={{ position: "relative", height }}>
        <div
          style={{
            position: "absolute",
            top: "50%",
            left: "50%",
            transform: "translate(-50%, -50%)",
          }}
        >
          Loading preview...
        </div>
      </div>
    );
  }

  // Show error if something went wrong
  if (error) {
    return (
      <div ref={containerRef} style={{ padding: "20px", color: "#e53935" }}>
        <h3>Error loading preview</h3>
        <pre>{error}</pre>
      </div>
    );
  }

  return <div ref={containerRef} style={{ height }}></div>;
};

export default StackBlitzPreview;
